# Generated by Django 4.2.7 on 2025-10-05 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diameter", models.FloatField()),
                ("velocity", models.FloatField()),
                ("density", models.FloatField()),
                ("impact_angle", models.FloatField()),
                ("impact_location", models.CharField(max_length=20)),
                ("impact_energy", models.FloatField()),
                ("tnt_equivalent", models.FloatField()),
                ("crater_diameter", models.FloatField()),
                ("seismic_magnitude", models.FloatField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
