# Generated by Django 4.2.7 on 2025-10-05 07:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asteroid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("neo_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("diameter_min", models.FloatField(blank=True, null=True)),
                ("diameter_max", models.FloatField(blank=True, null=True)),
                ("is_potentially_hazardous", models.BooleanField(default=False)),
                ("absolute_magnitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diameter", models.FloatField()),
                ("velocity", models.FloatField()),
                ("density", models.FloatField()),
                ("impact_angle", models.FloatField()),
                ("impact_location", models.CharField(max_length=20)),
                ("impact_energy", models.FloatField()),
                ("tnt_equivalent", models.FloatField()),
                ("crater_diameter", models.FloatField()),
                ("seismic_magnitude", models.FloatField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="CloseApproach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approach_date", models.DateTimeField()),
                ("velocity_kmh", models.FloatField()),
                ("velocity_kms", models.FloatField()),
                ("miss_distance_km", models.FloatField()),
                ("miss_distance_au", models.FloatField()),
                ("orbiting_body", models.CharField(default="Earth", max_length=50)),
                (
                    "asteroid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="close_approaches",
                        to="dashboard.asteroid",
                    ),
                ),
            ],
            options={
                "ordering": ["approach_date"],
            },
        ),
    ]
